### ISSUE TITLE
Auth type

### ISSUE THREAD

**Issue by imamahmadask** [nafiesl/grosir-obat#10]
Halo gan,

Saya berencana mengembangkan aplikasi ini untuk dua model user, yang satu untuk admin, yang satu untuk kasir. 

kasir mampu mengakses semua menu kecuali menu user karena menu user hanya untuk admin.

Saya mohon sarannya apakah saya bisa menambahkan role permission ?
sehingga nanti di file web route saya akan bedakan jika bukan admin maka tidak bisa mengakses route:resource dari user.

Trimakasih

**Comment by nafiesl** [comment]
Halo mas @imamahmadask,

Silakan mas, saran saya, gunakan fitur Gate dan authorization yang ada di laravel saja mas (tidak perlu menggunakan package dari luar). Karena fitur authorization bawaan laravel sudah cukup lengkap.

Kalau perlu gambaran untuk pengembangan sistem ini, bisa coba baca2 di panduan ini.
https://nafiesl.github.io/panduan-penjualan

**Comment by nafiesl** [comment]
Middleware, gate dan authorization bisa digunakan sama-sama mas. Itu lebih bagus.

Kelebihannya jika kita menggunakan gate dan authorization bawaan Laravel :
1. Kontrol hak akses sampai ke level model (record)
2. Semua jenis kontrol hak akses bisa kita buat dengan gate dan policy class
3. Aplikasi kita jadi lebih ramping

Kekurangannya:
- Saya belum temukan

Silakan mas @imamahmadask fork project ini, dan modifikasi sesuai kebutuhan (baik untuk pribadi maupun untuk kliennya/komersil). Syaratnya tetap mengikuti aturan dari MIT LICENSE, modifikasi bebas, tetapi tidak mengubah atau menghapus file [LICENSE](https://github.com/nafiesl/grosir-obat/blob/master/LICENSE) pada project ini. :grin:

Jika ingin pull-request ke repository ini, silakan, saya akan review nanti mas, sekaligus kita diskusikan sama-sama :+1:
