### ISSUE TITLE
print pdf error

### ISSUE THREAD

**Issue by boyet007** [nafiesl/grosir-obat#12]
muncul error : 

(1/1) FatalErrorExceptionMaximum execution time of 60 seconds exceeded
--
in Helpers.php (line 506)

**Comment by nafiesl** [comment]
mas @boyet007,
Bisa share screenshot errornya?

**Comment by boyet007** [comment]
pada waktu mau print pdf keluar error 
![image](https://user-images.githubusercontent.com/22869028/39580484-7af3a2e8-4f13-11e8-9348-1d70f0a8e06b.png)

**Comment by nafiesl** [comment]
Isi transaksinya berapa item mas? Sepertinya terlalu banyak ya, sampai dia ga cukup waktu untuk loadnya. Btw kalau pakai "Cetak Nota" ga error ya mas?

**Comment by nafiesl** [comment]
Error seperti itu untuk untuk semua transaksi atau beberapa transaksi tertentu mas?

**Comment by boyet007** [comment]
ngetest aja item 1 dah error.. cetak note lancar sih...

tadi sempet ngetes langsung di web nya ente kok ga error ya..

**Comment by nafiesl** [comment]
Sepertinya problemnya bukan di aplikasi mas, mungkin bisa mas troubleshoot sendiri problemnya ya. :+1:
