### ISSUE TITLE
Databasenya mana??

### ISSUE THREAD

**Issue by bgdaus** [nafiesl/grosir-obat#16]
Maaf bos databasenya mna??? Gmna mw tes aplikasinya

**Comment by nafiesl** [comment]
Databasenya tidak pakai file sql mas. Tapi pakai fitur migration dari framework laravel. Bisa dicek di folder `database/migrations`. Nanti table-table databasenya otomatis dibuat saat menjalankan **langkah ke 9** di [panduan cara install](https://github.com/nafiesl/grosir-obat#cara-install).
