### ISSUE TITLE
bagaimana caranya menambahkan table

### ISSUE THREAD

**Issue by pemakanwortel** [nafiesl/grosir-obat#17]
cara menambahkan table di produk gimana ya? saya mau tambahin harga modal, harga jual, harga kredit seperti itu pak, terimakasih

**Comment by nafiesl** [comment]
Mungkin yang dimaksud menambah kolom ya pak? Bisa dengan cara:
- Buat migration untuk nambah kolom baru, atau
- Langsung edit tabelnya dengan mysql client (phpmyadmin, adminer, heidisql).

Caranya sama saja seperti nembahkan kolom di table exsting biasanya di project laravel.

**Comment by pemakanwortel** [comment]
iya pak benar

localhost/product yang tampil hanya ini
#	Nama Produk	Satuan	Harga Tunai	Harga Kredit	Pilihan

saya ingin menambahkan Harga Grosir, saya belum tau caranya gimana , nambahin kolom berarti

**Comment by pemakanwortel** [comment]
udah aku tambahin kolom nya cash_grosir

http://prntscr.com/nbnbnp

masih belum tampil di sini nya pak
http://prntscr.com/nbnbwp

mohon pencerahanya pak

**Comment by nafiesl** [comment]
Nah itu sepertinya perlu pelajari dulu cara menampilkan data dari database di laravel blade. Fitur issue github ini dapat digunakan untuk melaporkan bug, atau problem saat installasi projectnya, bukan untuk konsultasi. Mohon maaf saya belum bisa bantu. :pray: 

Issue ini saya close ya.

**Comment by pemakanwortel** [comment]
mohon maaf pak, saya ijin menggunakan projek nya

**Comment by nafiesl** [comment]
Siap, silakan mas @pemakanwortel. :+1:

**Comment by pemakanwortel** [comment]
> Siap, silakan mas @pemakanwortel.

malam pak, bisa minta kontak whatsapnya

**Comment by nafiesl** [comment]
Mas @pemakanwortel, mohon kirim dulu email ya mas. Alamat email tertera di akun github saya.
