### ISSUE TITLE
Download detail transaksi as pdf time out

### ISSUE THREAD

**Issue by ahadimuhsin** [nafiesl/grosir-obat#18]
Siang gan

Saya suka kerjaan agan di sotware ini. Tapi saya menemukan kalo untuk download pdfnya time out. Saya lampirkan screenshot pesan errornya.

Spesifikasi sistem:
Windows 8.1 64 bit
PHP 7.3
MySQL
Laravel 5.8

![image](https://user-images.githubusercontent.com/26626855/59998992-fe714480-968a-11e9-83a8-e54d06a86add.png)
![image](https://user-images.githubusercontent.com/26626855/59999022-147f0500-968b-11e9-9f79-196f21d4e0cd.png)

**Comment by nafiesl** [comment]
halo mas @ahadimuhsin, terima kasih apresiasinya mas.

Known bug, seperti issue di #12, sepertinya ini kendala hanya terjadi di OS Windows ya. Saya belum bisa troubleshoot karena tidak pakai windows :pray:. Apakah mas bisa bantu kontribusi untuk cek problem ini?

Atau alternatifnya boleh buat PR untuk mengganti librari nya ke mPDF. :grin:

**Comment by lakuapik** [comment]
Halo, 

Dulu saya pernah alami hal serupa dengan lib `barryvdh/laravel-dompdf` di windows juga. 
Waktu itu browsing nemu solusi pakai helper `elixir` buat load asset di layout pdfnya.

Sebelumnya kalau pakai ini memang tidak bisa dan timeout
```php
{{ Html::style(url('css/pdf.css')) }}
```
atau
```php
<link rel="stylesheet" href="{{ asset('css/pdf.css') }}">
```

Kalau pakai ini bisa

``` php
<link rel="stylesheet" href="{{ elixir('css/pdf.css') }}">
```

**Comment by nafiesl** [comment]
Thank you bantuannya mas @lakuapik :pray:
