### ISSUE TITLE
Diskon tidak bekerja

### ISSUE THREAD

**Issue by imamahmadask** [nafiesl/grosir-obat#9]
Halo gan,
saya baru temukan nih aplikasinya, ketika saya coba demonya kok untuk diskon tidak bekerja ya. terimakasih

**Comment by nafiesl** [comment]
Halo mas.
Terima kasih infonya mas. Tapi apa bisa mohon dibantu capture diskonnya tidak bekerja dibagian mana?

Barusan saya coba input transaksi dengan diskon masih normal mas.

![shutter_20180423-005](https://user-images.githubusercontent.com/8721551/39125412-715122e0-4731-11e8-834b-ca249bb22c84.jpg)

**Comment by imamahmadask** [comment]
Halo mas,

berikut saya sertakan capturenya. saya coba masukkan diskon per-item 1000 rupiah
![image](https://user-images.githubusercontent.com/34978642/39127099-9b671f8a-4736-11e8-96db-19caad59972e.png)

ini setelah menekan tombol proses, diskon tetap tidak muncul.
![image](https://user-images.githubusercontent.com/34978642/39127122-ae7be560-4736-11e8-9e8b-49edf382eda0.png)

Apakah cara saya memasukkan diskon salah?
mohon bantuannya mas, saya butuh sekali aplikasi ini untuk dikembangkan.

Terimakasih.

**Comment by imamahmadask** [comment]
maaf, koreksi mas. 
barusan saya coba lagi ternyata setelah memasukkan nominal diskon harus tekan enter dahulu ya.
sebelumnya saya fikir akan auto generate ketika memasukkan nominal.

sekarang sudah berhasil. terimakasih banyak mas.

**Comment by nafiesl** [comment]
Oh ya, benar mas @imamahmadask harus tekan enter dulu, baru masuk angkanya.

Sip. terima kasih mas.

**Comment by boyet007** [comment]
enaknya kalo dikasih jquery keyup...

**Comment by nafiesl** [comment]
Agak rumit pengerjaannya mas @boyet007, tapi kalau mas berkenan buat PR untuk itu, nanti kita review sama-sama. :+1:

**Comment by boyet007** [comment]
programnya sudah mantap bro.. cuman saya agak kesulitan trace source code nya...
